# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司全称')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='公司简称')),
                ('Synopsis', models.CharField(max_length=50, verbose_name='公司简介')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'db_table': 'tb_company',
                'verbose_name_plural': '公司',
                'verbose_name': '公司',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='行业名称')),
            ],
            options={
                'db_table': 'tb_industry',
                'verbose_name_plural': '行业',
                'verbose_name': '行业',
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='稿件名')),
                ('createTime', models.DateField(verbose_name='发布日期')),
                ('issuer', models.CharField(max_length=10, verbose_name='发布人')),
                ('content', models.CharField(max_length=150, verbose_name='稿件文字内容')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'db_table': 'tb_manuscript',
                'verbose_name_plural': '历史稿件',
                'verbose_name': '历史稿件',
            },
        ),
        migrations.CreateModel(
            name='Reporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('mobile', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('Company_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Company', verbose_name='公司')),
                ('Industry_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Industry', verbose_name='行业')),
                ('Manuscript_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Manuscript', verbose_name='历史稿件')),
            ],
            options={
                'db_table': 'tb_reporters',
                'verbose_name_plural': '记者',
                'verbose_name': '记者',
            },
        ),
    ]
