# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180830_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='abc', max_length=20, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(default='abc', max_length=10, verbose_name='联系人'),
        ),
    ]
