# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180830_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
