# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180831_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='image',
        ),
        migrations.AlterField(
            model_name='company',
            name='Synopsis',
            field=models.CharField(max_length=500, verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=30, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='content',
            field=models.CharField(max_length=500, verbose_name='稿件文字内容'),
        ),
    ]
